CREATE SCHEMA bd_hotel_cop;

USE bd_hotel_cop;

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY (ID_FUNCIONARIO),
NOME_FUNCIONARIO VARCHAR (150) NOT NULL,
USUARIO_FUNCIONARIO VARCHAR (30) NOT NULL,
SENHA_FUNCIONARIO VARCHAR (9) NOT NULL,
PERMISSAO VARCHAR (50),
TELEFONE_FUNCIONARIO VARCHAR (11),
ENDERECO_FUNCIONARIO VARCHAR (45));

CREATE TABLE CLIENTES (
ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID_CLIENTE),
NOME_CLIENTE VARCHAR (150) NOT NULL,
CPF_CLIENTE VARCHAR (11) UNIQUE NOT NULL ,
TELEFONE_CLIENTE VARCHAR (11),
EMAIL_CLIENTE VARCHAR (30),
ENDERECO_CLIENTE VARCHAR (45),
ID_FUNCIONARIO INT NOT NULL,
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO));

CREATE TABLE QUARTOS (
ID_QUARTO INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID_QUARTO),
TIPO_QUARTO VARCHAR (45) NOT NULL,
VALOR_TIPO_QUARTO FLOAT NOT NULL,
STATUS_QUARTO VARCHAR (45) NOT NULL,
ANDAR INT NOT NULL ,
NUMERO_QUARTO INT NOT NULL UNIQUE);

CREATE TABLE RESERVAS (
ID_RESERVA INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID_RESERVA),
DATA_INICIAL DATE NOT NULL,
DATA_FINAL DATE NOT NULL,
STATUS_RESERVA VARCHAR (45),
ID_CLIENTE INT NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE RESERVA_QUARTOS (
ID_RESERVA INT,
ID_QUARTO INT,
PRIMARY KEY (ID_RESERVA, ID_QUARTO), -- CHAVE COMPOSTA
FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS (ID_RESERVA) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ID_QUARTO) REFERENCES QUARTOS (ID_QUARTO) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE PAGAMENTOS (
ID_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID_PAGAMENTO),
VALOR FLOAT, 
TIPO_PAGAMENTO VARCHAR (45),
STATUS_PAGAMENTO VARCHAR (50),
ID_RESERVA INT,
FOREIGN KEY (ID_RESERVA) REFERENCES reservas (ID_RESERVA) ON DELETE CASCADE ON UPDATE CASCADE);